### ISSUE TITLE
Problem using the example file format

### ISSUE THREAD

**Issue by acnazarejr** [simondenman/SemanticSearchChallengeAVSS18#2]
If we use the example file format for TASK 1 to generate results using a validation data set (created as a subset of provided training data), and plot the CMC curve, the resulting sound estranges. It's like a random result. 

To fix, we need to increase the query id in 1 for all queries. 

I think the problem is in the function `ParseGroundTruth(mainfile)` of file `task_1/ground_truth.py`, because in this function the id starts in 1, instead 0 , as well as the test file provided by you.

**Comment by simondenman** [comment]
I've gone through the code and I don't really understand the problem your outlining. On my two test files I get the correct CMC curves. Could you give me some more info as to the problem, or just a way to reproduce the problem you have found?

**Comment by simondenman** [comment]
I think I have just found the problem you were referring to. Task1/eval.py has been adjusted to correct

**Comment by acnazarejr** [comment]
Thank you! I send another solution as a pull request.
